apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: bottomline
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: bottom1
        #command: ["/bin/sleep", "3650d"]
        env:
        - name: JAVA_ARGS
          value: "-Xms1024m -Xmx1792m"
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 500m
            memory: 2048Mi
          limits:
            cpu: 500m
            memory: 2048Mi
        #lifecycle:
        #    postStart:
        #      exec:
        #        command: ["/bin/sh", "-c", "cd /Quantify_Ubuntu/Package/engine/ && ./startservice.sh"]
      nodeSelector:
        key= value
